--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2
-- Dumped by pg_dump version 15.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: avion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.avion (
    dt_fabrication date,
    id smallint NOT NULL,
    modele_id smallint,
    nom character varying(255) NOT NULL
);


ALTER TABLE public.avion OWNER TO postgres;

--
-- Name: avion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.avion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.avion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: g_reservation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.g_reservation (
    id smallint NOT NULL,
    valeur smallint NOT NULL,
    label character varying(255) NOT NULL
);


ALTER TABLE public.g_reservation OWNER TO postgres;

--
-- Name: g_reservation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.g_reservation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.g_reservation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: modele; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.modele (
    id smallint NOT NULL,
    label character varying(255) NOT NULL
);


ALTER TABLE public.modele OWNER TO postgres;

--
-- Name: modele_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.modele ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.modele_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prix_siege; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prix_siege (
    id integer NOT NULL,
    prix double precision NOT NULL,
    type_siege_id smallint NOT NULL,
    vol_id integer NOT NULL
);


ALTER TABLE public.prix_siege OWNER TO postgres;

--
-- Name: prix_siege_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.prix_siege ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prix_siege_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: promotion_reservation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.promotion_reservation (
    id integer NOT NULL,
    nb_siege integer NOT NULL,
    off double precision,
    type_siege_id smallint NOT NULL,
    vol_id integer NOT NULL
);


ALTER TABLE public.promotion_reservation OWNER TO postgres;

--
-- Name: promotion_reservation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.promotion_reservation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.promotion_reservation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reservation (
    id integer NOT NULL,
    statue smallint,
    user_id integer NOT NULL,
    vol_id integer NOT NULL,
    dt_reservation timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.reservation OWNER TO postgres;

--
-- Name: reservation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reservation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role (
    id smallint NOT NULL,
    label character varying(255)
);


ALTER TABLE public.role OWNER TO postgres;

--
-- Name: role_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.role_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.role_seq OWNER TO postgres;

--
-- Name: siege_avion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.siege_avion (
    avion_id smallint NOT NULL,
    id integer NOT NULL,
    nb_siege smallint NOT NULL,
    type_siege_id smallint NOT NULL
);


ALTER TABLE public.siege_avion OWNER TO postgres;

--
-- Name: siege_avion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.siege_avion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.siege_avion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: type_siege; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.type_siege (
    id smallint NOT NULL,
    label character varying(255) NOT NULL
);


ALTER TABLE public.type_siege OWNER TO postgres;

--
-- Name: type_siege_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.type_siege ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.type_siege_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    role_id smallint NOT NULL,
    email character varying(50),
    pwd character varying(50) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ville; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ville (
    id smallint NOT NULL,
    label character varying(20) NOT NULL
);


ALTER TABLE public.ville OWNER TO postgres;

--
-- Name: ville_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ville ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ville_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vol; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vol (
    avion_id smallint,
    id integer NOT NULL,
    last_annulation_reservation smallint,
    last_reservation smallint,
    ville_arrive_id smallint,
    ville_depart_id smallint,
    date_vol timestamp(6) without time zone,
    statue character varying(255) NOT NULL,
    CONSTRAINT vol_statue_check CHECK (((statue)::text = ANY ((ARRAY['ACTIF'::character varying, 'ANNULE'::character varying, 'RETARDE'::character varying, 'TERMINE'::character varying])::text[])))
);


ALTER TABLE public.vol OWNER TO postgres;

--
-- Name: vol_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.vol ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: avion avion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.avion
    ADD CONSTRAINT avion_pkey PRIMARY KEY (id);


--
-- Name: g_reservation g_reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.g_reservation
    ADD CONSTRAINT g_reservation_pkey PRIMARY KEY (id);


--
-- Name: modele modele_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.modele
    ADD CONSTRAINT modele_pkey PRIMARY KEY (id);


--
-- Name: prix_siege prix_siege_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prix_siege
    ADD CONSTRAINT prix_siege_pkey PRIMARY KEY (id);


--
-- Name: promotion_reservation promotion_reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.promotion_reservation
    ADD CONSTRAINT promotion_reservation_pkey PRIMARY KEY (id);


--
-- Name: reservation reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT reservation_pkey PRIMARY KEY (id);


--
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- Name: siege_avion siege_avion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.siege_avion
    ADD CONSTRAINT siege_avion_pkey PRIMARY KEY (id);


--
-- Name: type_siege type_siege_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.type_siege
    ADD CONSTRAINT type_siege_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: ville ville_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ville
    ADD CONSTRAINT ville_pkey PRIMARY KEY (id);


--
-- Name: vol vol_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vol
    ADD CONSTRAINT vol_pkey PRIMARY KEY (id);


--
-- Name: users fk4qu1gr772nnf6ve5af002rwya; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk4qu1gr772nnf6ve5af002rwya FOREIGN KEY (role_id) REFERENCES public.role(id);


--
-- Name: vol fk4sme09xyncqxycf8c1qr41nb6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vol
    ADD CONSTRAINT fk4sme09xyncqxycf8c1qr41nb6 FOREIGN KEY (ville_arrive_id) REFERENCES public.ville(id);


--
-- Name: avion fkasudhdmb8oworu9jehw9qw4to; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.avion
    ADD CONSTRAINT fkasudhdmb8oworu9jehw9qw4to FOREIGN KEY (modele_id) REFERENCES public.modele(id);


--
-- Name: siege_avion fkel741r5h59jlvevh3qpnsay2k; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.siege_avion
    ADD CONSTRAINT fkel741r5h59jlvevh3qpnsay2k FOREIGN KEY (type_siege_id) REFERENCES public.type_siege(id);


--
-- Name: reservation fkfj4ypmo6yenc9x7fl8ndcu29b; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT fkfj4ypmo6yenc9x7fl8ndcu29b FOREIGN KEY (vol_id) REFERENCES public.vol(id);


--
-- Name: vol fkg6yy40p9plu2nw0abg38l765d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vol
    ADD CONSTRAINT fkg6yy40p9plu2nw0abg38l765d FOREIGN KEY (ville_depart_id) REFERENCES public.ville(id);


--
-- Name: vol fki36u7096ahgjbjwinm85pfwjw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vol
    ADD CONSTRAINT fki36u7096ahgjbjwinm85pfwjw FOREIGN KEY (avion_id) REFERENCES public.avion(id);


--
-- Name: siege_avion fklpmyro8efdm3pqfiabojp9l2y; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.siege_avion
    ADD CONSTRAINT fklpmyro8efdm3pqfiabojp9l2y FOREIGN KEY (avion_id) REFERENCES public.avion(id);


--
-- Name: prix_siege fkmu9kqs8bujiqgs4vciyfpj6rm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prix_siege
    ADD CONSTRAINT fkmu9kqs8bujiqgs4vciyfpj6rm FOREIGN KEY (type_siege_id) REFERENCES public.type_siege(id);


--
-- Name: promotion_reservation fkpc7bvd0rlvlo9auvgcin91m8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.promotion_reservation
    ADD CONSTRAINT fkpc7bvd0rlvlo9auvgcin91m8 FOREIGN KEY (type_siege_id) REFERENCES public.type_siege(id);


--
-- Name: prix_siege fkqiu05s2tn33kxbtavkicugm1d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prix_siege
    ADD CONSTRAINT fkqiu05s2tn33kxbtavkicugm1d FOREIGN KEY (vol_id) REFERENCES public.vol(id);


--
-- Name: reservation fkrea93581tgkq61mdl13hehami; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT fkrea93581tgkq61mdl13hehami FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: promotion_reservation fksa9mdyp58t1a3cgg0d7v43dr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.promotion_reservation
    ADD CONSTRAINT fksa9mdyp58t1a3cgg0d7v43dr FOREIGN KEY (vol_id) REFERENCES public.vol(id);


--
-- PostgreSQL database dump complete
--

